spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;mode=mysql;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
  jpa:
    show-sql: true

logging:
  level:
    cn:
      celess:
        house:
          util: debug
