spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;mode=mysql;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      enabled: on
      platform: h2
      encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    banner-mode: off

logging:
  level:
    cn:
      celess:
        house:
          util: debug