# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Angular Github Actions
      - uses: mayurrawte/github-angular-actions@latest
      - run: ng lint
